SPRINGER_URL = "http://api.springernature.com/meta/v2/json"
BOTID = "@SpringerNatureBot"
DAILY_ARTICLES = list()  # become empty every day at 2 PM (BST)
JID = {"Nature": 41586,
       "NatureGenetics": 41588,
       "NatureReviewsCardiology": 41569,
       "NatureReviewsClinicalOncology": 41571,
       "NatureReviewsDiseasePrimers": 41572,
       "NatureReviewsEndocrinology": 41574,
       "NatureReviewsGastroenterologyHepatology": 41575,
       "NatureReviewsNephrology": 41581,
       "NatureReviewsGenetics": 41576,
       "NatureReviewsMolecularCellBiology": 41580,
       "NatureReviewsNeuroscience": 41583,
       "NatureReviewsMethodsPrimers": 43586,
       "NatureReviewsNeurology": 41582,
       "NatureReviewsRheumatology": 41584,
       "NatureReviewsUrology": 41585,
       "NatureReviewsCancer": 41568,
       "NatureReviewsImmunology": 41577,
       "NatureReviewsDrugDiscovery": 41573,
       "NatureReviewsMicrobiology": 41579,
       "NatureReviewsChemistry": 41570,
       "NatureReviewsEarthEnvironment": 43017,
       "NatureReviewsMaterials": 41578,
       "NatureReviewsPhysics": 42254}
JCHANNEL = {"Nature": "@NatureReviewsLife",
            "NatureGenetics": "@NatureGenetics",
            "NatureReviewsCardiology": "@NatureReviewsClinical",
            "NatureReviewsClinicalOncology": "@NatureReviewsClinical",
            "NatureReviewsDiseasePrimers": "@NatureReviewsClinical",
            "NatureReviewsEndocrinology": "@NatureReviewsClinical",
            "NatureReviewsGastroenterologyHepatology": "@NatureReviewsClinical",
            "NatureReviewsNephrology": "@NatureReviewsClinical",
            "NatureReviewsGenetics": "@NatureReviewsLife",
            "NatureReviewsMolecularCellBiology": "@NatureReviewsLife",
            "NatureReviewsNeuroscience": "@NatureReviewsLife",
            "NatureReviewsMethodsPrimers": "@NatureReviewsPhysical",
            "NatureReviewsNeurology": "@NatureReviewsClinical",
            "NatureReviewsRheumatology": "@NatureReviewsClinical",
            "NatureReviewsUrology": "@NatureReviewsClinical",
            "NatureReviewsCancer": "@NatureReviewsLife",
            "NatureReviewsImmunology": "@NatureReviewsLife",
            "NatureReviewsDrugDiscovery": "@NatureReviewsLife",
            "NatureReviewsMicrobiology": "@NatureReviewsLife",
            "NatureReviewsChemistry": "@NatureReviewsPhysical",
            "NatureReviewsEarthEnvironment": "@NatureReviewsPhysical",
            "NatureReviewsMaterials": "@NatureReviewsPhysical",
            "NatureReviewsPhysics": "@NatureReviewsPhysical"}
