SPRINGER_URL = "http://api.springernature.com/meta/v2/json"
BOTID = "@SpringerNatureBot"
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36 OPR/40.0.2308.81'
}
JID = {"Nature": 41586,
       "NatureMachineIntelligence": 42256,
       "NatureGenetics": 41588,
       "NatureReviewsCardiology": 41569,
       "NatureReviewsClinicalOncology": 41571,
       "NatureReviewsDiseasePrimers": 41572,
       "NatureReviewsEndocrinology": 41574,
       "NatureReviewsGastroenterologyHepatology": 41575,
       "NatureReviewsNephrology": 41581,
       "NatureReviewsGenetics": 41576,
       "NatureReviewsMolecularCellBiology": 41580,
       "NatureReviewsNeuroscience": 41583,
       "NatureReviewsMethodsPrimers": 43586,
       "NatureReviewsNeurology": 41582,
       "NatureReviewsRheumatology": 41584,
       "NatureReviewsUrology": 41585,
       "NatureReviewsCancer": 41568,
       "NatureReviewsImmunology": 41577,
       "NatureReviewsDrugDiscovery": 41573,
       "NatureReviewsMicrobiology": 41579,
       "NatureReviewsChemistry": 41570,
       "NatureReviewsEarthEnvironment": 43017,
       "NatureReviewsMaterials": 41578,
       "NatureReviewsPhysics": 42254
       }
JCHANNEL = {"Nature": "@NatureReviewsLife",
            "NatureMachineIntelligence": "@NatureMachineIntelligence",
            "NatureGenetics": "@NatureGenetics",
            "NatureReviewsCardiology": "@NatureReviewsClinical",
            "NatureReviewsClinicalOncology": "@NatureReviewsClinical",
            "NatureReviewsDiseasePrimers": "@NatureReviewsClinical",
            "NatureReviewsEndocrinology": "@NatureReviewsClinical",
            "NatureReviewsGastroenterologyHepatology": "@NatureReviewsClinical",
            "NatureReviewsNephrology": "@NatureReviewsClinical",
            "NatureReviewsGenetics": "@NatureReviewsLife",
            "NatureReviewsMolecularCellBiology": "@NatureReviewsLife",
            "NatureReviewsNeuroscience": "@NatureReviewsLife",
            "NatureReviewsMethodsPrimers": "@NatureReviewsPhysical",
            "NatureReviewsNeurology": "@NatureReviewsClinical",
            "NatureReviewsRheumatology": "@NatureReviewsClinical",
            "NatureReviewsUrology": "@NatureReviewsClinical",
            "NatureReviewsCancer": "@NatureReviewsLife",
            "NatureReviewsImmunology": "@NatureReviewsLife",
            "NatureReviewsDrugDiscovery": "@NatureReviewsLife",
            "NatureReviewsMicrobiology": "@NatureReviewsLife",
            "NatureReviewsChemistry": "@NatureReviewsPhysical",
            "NatureReviewsEarthEnvironment": "@NatureReviewsPhysical",
            "NatureReviewsMaterials": "@NatureReviewsPhysical",
            "NatureReviewsPhysics": "@NatureReviewsPhysical"
            }
